# Generated by Django 5.1.2 on 2024-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_velo_code_reservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velo',
            name='velo',
            field=models.CharField(choices=[('Velo 1', 'Velo 1'), ('Velo 2', 'Velo 2')], default='Velo1', max_length=6),
        ),
    ]
