# Generated by Django 5.1.2 on 2024-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_velo_velo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
