# Generated by Django 5.1.2 on 2024-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_complete_alter_reservation_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'Élève'), ('moderateur', 'Modérateur')], default='eleve', max_length=10),
        ),
    ]
