# Generated by Django 5.1.2 on 2024-12-02 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name="Description de l'incident")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incident_photos/', verbose_name='Photo (facultative)')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('velo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.velo', verbose_name='Vélo')),
            ],
        ),
    ]
