# Generated by Django 5.1.2 on 2024-10-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_velo_rename_heure_reservation_reservation_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
