# Generated by Django 5.1.2 on 2024-12-11 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
